sets.exported={
    main="Fettering Blade",
    sub="Demersal Degen",
    range={ name="Anarchy +3", augments={'Delay:+60','TP Bonus +100',}},
    ammo="Eminent Bullet",
    head="Lak. Hat +1",
    hands="Meg. Gloves +2",
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    feet={ name="Herculean Boots", augments={'Attack+23','"Triple Atk."+3','STR+3','Accuracy+8',}},
    neck="Loricate Torque",
    waist="Flume Belt +1",
    left_ear="Brutal Earring",
    right_ear="Suppanomimi",
    left_ring="Defending Ring",
    right_ring="Karieyh Ring",
    back={ name="Camulus's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','Crit.hit rate+10',}},
}